services:
  app:
    build:
      context: .
    container_name: app
    env_file:
      - ${ENV_FILE} # .env for production or .env.development for dev environment
      - .env.secrets
    volumes:
      - .:/tinygen
    ports:
      - "8000:8000"
